steps:
  # [Create build trigger for the creation of the bucket to store logs]
  - id: 'create trigger for build logs bucket'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        source buckets/trigger.sh
  # [Run trigger]
  - id: 'run trigger'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        gcloud beta builds triggers run --branch=$BRANCH_NAME build-log-bucket-trigger