steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"

  - id: 'tf init'
    name: 'hashicorp/terraform:0.13.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init

  # [START tf-plan]
  - id: 'tf plan'
    name: 'hashicorp/terraform:0.13.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform plan
  # [END tf-plan]

  # [START tf-apply]
  - id: 'tf apply'
    name: 'hashicorp/terraform:0.13.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ $BRANCH_NAME = "main" ]; then
          terraform apply -auto-approve
        else
          echo "***************************** SKIPPING APPLYING *******************************"
          echo "Branch '$BRANCH_NAME' does not represent an oficial environment."
          echo "*******************************************************************************"
        fi
# [END tf-apply]